  CREATE TABLE "LABIRINTOS" 
   (	"LABIRINTO_ID" NUMBER, 
	"DESCRICAO" VARCHAR2(100), 
	 PRIMARY KEY ("LABIRINTO_ID")
  USING INDEX  ENABLE
   );

  CREATE TABLE "LABIRINTOS_MATRIZ" 
   (	"LABIRINTO_ID" NUMBER, 
	"LINHA" NUMBER, 
	"LAYOUT" VARCHAR2(14) NOT NULL ENABLE, 
	 CHECK (linha BETWEEN 0 AND 13) ENABLE, 
	 PRIMARY KEY ("LABIRINTO_ID", "LINHA")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "LABIRINTOS_MATRIZ" ADD FOREIGN KEY ("LABIRINTO_ID")
	  REFERENCES "LABIRINTOS" ("LABIRINTO_ID") ENABLE;

